# Generated by Django 6.1.1 on 2026-09-29 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('superficie', models.IntegerField()),
                ('consommation_electrique', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('duree_de_vie', models.IntegerField()),
                ('cout_maintenance', models.IntegerField()),
                ('superficie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('tva', models.IntegerField()),
                ('tarif_electrique', models.IntegerField()),
                ('salaire_minimum', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix_de_vente', models.IntegerField()),
                ('duree_de_vie', models.IntegerField()),
                ('nombre_par_palette', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cout', models.IntegerField()),
                ('quantite_produits', models.IntegerField()),
                ('heures_de_travail', models.IntegerField()),
                ('consommation_electrique', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='high_level.machine')),
                ('operation_suivante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='high_level.operation')),
            ],
        ),
        migrations.CreateModel(
            name='PointDeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('heures_de_travail', models.IntegerField()),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='high_level.lieu')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_produits', models.IntegerField()),
                ('reduction', models.IntegerField()),
                ('point_de_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='high_level.pointdevente')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='high_level.produit')),
            ],
        ),
        migrations.CreateModel(
            name='QuantiteMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='high_level.machine')),
            ],
            options={
                'verbose_name_plural': 'QuantiteMachines',
            },
        ),
        migrations.AddField(
            model_name='lieu',
            name='machines',
            field=models.ManyToManyField(to='high_level.quantitemachine'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('palettes_max', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='high_level.produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pointdevente',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='high_level.stock'),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_palettes', models.IntegerField()),
                ('cout', models.IntegerField()),
                ('delai', models.IntegerField()),
                ('arrivee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='high_level.lieu')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='high_level.lieu')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('taxe_immobiliere', models.IntegerField()),
                ('prix_m2', models.IntegerField()),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='high_level.pays')),
            ],
        ),
        migrations.AddField(
            model_name='lieu',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='high_level.ville'),
        ),
        migrations.CreateModel(
            name='PrixProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_achat', models.IntegerField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='high_level.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='high_level.produit')),
            ],
            options={
                'unique_together': {('produit', 'fournisseur')},
            },
        ),
    ]
