# Generated by Django 6.1.1 on 2026-09-29 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_level', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.ville'),
        ),
    ]
